# Загрузка библиотек

In [27]:
import pandas as pd
from tqdm import tqdm
import psycopg2
import sqlite3
from datetime import date

# Загрузка данных в базу данных

In [24]:
def get_conn(dbname, user, password, host, port):
    return psycopg2.connect(dbname=dbname, user=user, password=password, host=host, port=port)

In [3]:
dbname = "Routes_tracks" 
user = "postgres" 
password = "86754231qaZ" 
host = "localhost" 
port = "5434" 

conn = get_conn(dbname, user, password, host, port)

In [25]:
conn = sqlite3.connect("database.db")

In [4]:
result_data = pd.read_csv("result_data.csv")

result_data

,track_id,DateTime,latitude,longitude,altitude,temp,region,water_dist,building_dist,green_dist,water_area,building_area,green_area
0,1,2022-03-23 03:47:32,28.526319,77.205764,233.448227,21.00,Region 1,483.748137,17.263341,219.293124,9.614001,1361.365668,9.068051
1,1,2022-03-23 03:47:33,28.526304,77.205761,233.366989,16.00,Region 1,484.978274,18.888186,220.963695,9.614001,1361.576094,9.068051
2,1,2022-03-23 03:47:34,28.526298,77.205760,233.334747,25.00,Region 1,485.481786,19.533009,221.631384,9.614001,1353.855885,9.068051
3,1,2022-03-23 03:47:35,28.526288,77.205757,233.280121,19.00,Region 1,486.250814,20.664223,222.748454,9.614001,1350.015010,9.068051
4,1,2022-03-23 03:47:36,28.526277,77.205755,233.228973,21.00,Region 1,487.167542,21.860118,223.973323,9.614001,1350.783267,9.068051
...,...,...,...,...,...,...,...,...,...,...,...,...,...
365995,2,2022-12-31 21:00:00,28.520591,77.203003,235.674286,-14.45,Region 2,-1.000000,5.059959,437.808130,-1.000000,1851.158175,7450.647125
365996,2,2022-12-31 21:00:00,28.520587,77.202993,235.622757,-14.45,Region 2,-1.000000,5.173381,436.776815,-1.000000,1846.372356,7450.647125
365997,2,2022-12-31 21:00:00,28.520584,77.202984,235.570862,-14.45,Region 2,-1.000000,5.390939,435.858069,-1.000000,1850.204349,7450.647125
365998,2,2022-12-31 21:00:00,28.520580,77.202974,235.519058,-14.45,Region 2,-1.000000,5.878070,434.827106,-1.000000,1848.577678,7450.647125
365999,2,2022-12-31 21:00:00,28.520577,77.202964,235.466415,-14.45,Region 2,-1.000000,6.400970,433.811656,-1.000000,1850.197701,7450.647125

In [9]:
result_data["DateTime"] = pd.to_datetime(result_data["DateTime"])

In [12]:
def get_season(row_date):
    month = row_date.month
    if month in [12, 1, 2]:
        season = "Зима"
    elif month in [3, 4, 5]:
        season = "Весна"
    elif month in [6, 7, 8]:
        season = "Лето"
    else:
        season = "Осень"
    return season

In [13]:
result_data["season"] = result_data["DateTime"].apply(get_season)

result_data

,track_id,DateTime,latitude,longitude,altitude,temp,region,water_dist,building_dist,green_dist,water_area,building_area,green_area,season
0,1,2022-03-23 03:47:32,28.526319,77.205764,233.448227,21.00,Region 1,483.748137,17.263341,219.293124,9.614001,1361.365668,9.068051,Весна
1,1,2022-03-23 03:47:33,28.526304,77.205761,233.366989,16.00,Region 1,484.978274,18.888186,220.963695,9.614001,1361.576094,9.068051,Весна
2,1,2022-03-23 03:47:34,28.526298,77.205760,233.334747,25.00,Region 1,485.481786,19.533009,221.631384,9.614001,1353.855885,9.068051,Весна
3,1,2022-03-23 03:47:35,28.526288,77.205757,233.280121,19.00,Region 1,486.250814,20.664223,222.748454,9.614001,1350.015010,9.068051,Весна
4,1,2022-03-23 03:47:36,28.526277,77.205755,233.228973,21.00,Region 1,487.167542,21.860118,223.973323,9.614001,1350.783267,9.068051,Весна
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365995,2,2022-12-31 21:00:00,28.520591,77.203003,235.674286,-14.45,Region 2,-1.000000,5.059959,437.808130,-1.000000,1851.158175,7450.647125,Зима
365996,2,2022-12-31 21:00:00,28.520587,77.202993,235.622757,-14.45,Region 2,-1.000000,5.173381,436.776815,-1.000000,1846.372356,7450.647125,Зима
365997,2,2022-12-31 21:00:00,28.520584,77.202984,235.570862,-14.45,Region 2,-1.000000,5.390939,435.858069,-1.000000,1850.204349,7450.647125,Зима
365998,2,2022-12-31 21:00:00,28.520580,77.202974,235.519058,-14.45,Region 2,-1.000000,5.878070,434.827106,-1.000000,1848.577678,7450.647125,Зима
365999,2,2022-12-31 21:00:00,28.520577,77.202964,235.466415,-14.45,Region 2,-1.000000,6.400970,433.811656,-1.000000,1850.197701,7450.647125,Зима

In [18]:
result_data["hour"] = result_data["DateTime"].apply(lambda x: x.hour)

In [20]:
result_data

,track_id,DateTime,latitude,longitude,altitude,temp,region,water_dist,building_dist,green_dist,water_area,building_area,green_area,season,hour
0,1,2022-03-23 03:47:32,28.526319,77.205764,233.448227,21.00,Region 1,483.748137,17.263341,219.293124,9.614001,1361.365668,9.068051,Весна,3
1,1,2022-03-23 03:47:33,28.526304,77.205761,233.366989,16.00,Region 1,484.978274,18.888186,220.963695,9.614001,1361.576094,9.068051,Весна,3
2,1,2022-03-23 03:47:34,28.526298,77.205760,233.334747,25.00,Region 1,485.481786,19.533009,221.631384,9.614001,1353.855885,9.068051,Весна,3
3,1,2022-03-23 03:47:35,28.526288,77.205757,233.280121,19.00,Region 1,486.250814,20.664223,222.748454,9.614001,1350.015010,9.068051,Весна,3
4,1,2022-03-23 03:47:36,28.526277,77.205755,233.228973,21.00,Region 1,487.167542,21.860118,223.973323,9.614001,1350.783267,9.068051,Весна,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365995,2,2022-12-31 21:00:00,28.520591,77.203003,235.674286,-14.45,Region 2,-1.000000,5.059959,437.808130,-1.000000,1851.158175,7450.647125,Зима,21
365996,2,2022-12-31 21:00:00,28.520587,77.202993,235.622757,-14.45,Region 2,-1.000000,5.173381,436.776815,-1.000000,1846.372356,7450.647125,Зима,21
365997,2,2022-12-31 21:00:00,28.520584,77.202984,235.570862,-14.45,Region 2,-1.000000,5.390939,435.858069,-1.000000,1850.204349,7450.647125,Зима,21
365998,2,2022-12-31 21:00:00,28.520580,77.202974,235.519058,-14.45,Region 2,-1.000000,5.878070,434.827106,-1.000000,1848.577678,7450.647125,Зима,21
365999,2,2022-12-31 21:00:00,28.520577,77.202964,235.466415,-14.45,Region 2,-1.000000,6.400970,433.811656,-1.000000,1850.197701,7450.647125,Зима,21

In [21]:
result_data.to_sql("result_data", conn)

366000

In [22]:
result_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366000 entries, 0 to 365999
Data columns (total 15 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   track_id       366000 non-null  int64
 1   DateTime       366000 non-null  datetime64[ns]
 2   latitude       366000 non-null  float64
 3   longitude      366000 non-null  float64
 4   altitude       366000 non-null  float64
 5   temp           366000 non-null  float64
 6   region         366000 non-null  object
 7   water_dist     366000 non-null  float64
 8   building_dist  366000 non-null  float64
 9   green_dist     366000 non-null  float64
 10  water_area     366000 non-null  float64
 11  building_area  366000 non-null  float64
 12  green_area     366000 non-null  float64
 13  season         366000 non-null  object
 14  hour           366000 non-null  int64
dtypes: datetime64[ns](1), float64(10), int64(2), object(2)
memory usage: 41.9+ MB